<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Use database seeds to create first user with email admin@admin.com and password 'password'
        DB::table('users')->insert([
            'name' => 'Admin',
            'email' => 'admin@admin.com',
            'password' => bcrypt('password'),
            // this is a bad practice, the api tokens need to be generated by the users and also be hashed. But since this demo requires a very simple auth approach, we hardcode the admin user's api token
            'api_token' => 'secret',
        ]);
    }
}
